In [1]:
from google.cloud import bigquery
import os
import pandas as pd

In [2]:
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/Users/khaledkhatib/Downloads/BigQueryCreds.json"

In [3]:
client = bigquery.Client()

In [15]:
query_job = client.query("""
    SELECT visitorId,visitStartTime,date,totals.visits,totals.hits,totals.timeonsite,totals.bounces,totals.transactions,totals.transactionrevenue,totals.newvisits,totals.timeonscreen,trafficsource.campaign,trafficsource.keyword,device.ismobile,device.operatingsystem,geonetwork.country,geonetwork.city,geonetwork.networkdomain FROM `bigquery-public-data.google_analytics_sample.ga_sessions_20160901`""")

results = query_job.result()  # Waits for job to complete.

In [16]:
bq_df = results.to_dataframe()

In [17]:
bq_df

,visitorId,visitStartTime,date,visits,hits,timeonsite,bounces,transactions,transactionrevenue,newvisits,timeonscreen,campaign,keyword,ismobile,operatingsystem,country,city,networkdomain
0,None,1472743915,20160901,1,1,NaN,1.0,NaN,NaN,NaN,None,(not set),(not provided),True,Android,Australia,Sydney,tpgi.com.au
1,None,1472743125,20160901,1,1,NaN,1.0,NaN,NaN,1.0,None,(not set),(not provided),False,Windows,France,Paris,0pb.org
2,None,1472728566,20160901,1,1,NaN,1.0,NaN,NaN,1.0,None,(not set),None,False,Macintosh,China,not available in demo dataset,16clouds.com
3,None,1472792306,20160901,1,1,NaN,1.0,NaN,NaN,1.0,None,(not set),(not provided),False,Windows,Belgium,(not set),m247.com
4,None,1472783251,20160901,1,1,NaN,1.0,NaN,NaN,NaN,None,(not set),(not provided),False,Macintosh,United States,New York,optonline.net
5,None,1472745090,20160901,1,1,NaN,1.0,NaN,NaN,NaN,None,(not set),(not provided),False,Macintosh,United Kingdom,London,(not set)
6,None,1472728182,20160901,1,1,NaN,1.0,NaN,NaN,1.0,None,(not set),(not provided),False,Windows,Indonesia,Jakarta,bankmandiri.co.id
7,None,1472729660,20160901,1,1,NaN,1.0,NaN,NaN,NaN,None,(not set),(not provided),False,Macintosh,Spain,Madrid,ono.com
8,None,1472715773,20160901,1,1,NaN,1.0,NaN,NaN,1.0,None,(not set),(not provided),False,Windows,Italy,not available in demo dataset,fastwebnet.it
9,None,1472749554,20160901,1,1,NaN,1.0,NaN,NaN,1.0,None,(not set),None,True,Android,India,not available in demo dataset,unknown.unknown
10,None,1472741845,20160901,1,1,NaN,1.0,NaN,NaN,NaN,None,(not set),None,False,Macintosh,United States,Austin,(not set)
11,None,1472729049,20160901,1,1,NaN,1.0,NaN,NaN,NaN,None,(not set),(not provided),False,Macintosh,Germany,not available in demo dataset,t-ipconnect.de
12,None,1472742813,20160901,1,1,NaN,1.0,NaN,NaN,1.0,None,(not set),(not provided),False,Windows,United States,not available in demo dataset,(not set)
13,None,1472724819,20160901,1,1,NaN,1.0,NaN,NaN,1.0,None,(not set),(not provided),False,Windows,India,Chennai,unknown.unknown
14,None,1472731287,20160901,1,1,NaN,1.0,NaN,NaN,NaN,None,(not set),(not provided),False,Windows,United Kingdom,not available in demo dataset,unknown.unknown
15,None,1472741621,20160901,1,1,NaN,1.0,NaN,NaN,1.0,None,(not set),(not provided),False,Macintosh,Germany,not available in demo dataset,(not set)
16,None,1472753593,20160901,1,1,NaN,1.0,NaN,NaN,1.0,None,(not set),(not provided),False,Chrome OS,United States,not available in demo dataset,unknown.unknown
17,None,1472726877,20160901,1,1,NaN,1.0,NaN,NaN,1.0,None,(not set),(not provided),False,Macintosh,Netherlands,not available in demo dataset,fontys.nl
18,None,1472725209,20160901,1,1,NaN,1.0,NaN,NaN,1.0,None,(not set),(not provided),False,Windows,Indonesia,Jakarta,qwords.net
19,None,1472755577,20160901,1,1,NaN,1.0,NaN,NaN,1.0,None,(not set),google shop,True,Android,Nigeria,not available in demo dataset,unknown.unknown
20,None,1472798489,20160901,1,1,NaN,1.0,NaN,NaN,1.0,None,(not set),(not provided),False,Windows,Taiwan,(not set),unknown.unknown
21,None,1472768763,20160901,1,1,NaN,1.0,NaN,NaN,1.0,None,(not set),None,True,Android,United States,(not set),google.com
22,None,1472779856,20160901,1,1,NaN,1.0,NaN,NaN,1.0,None,(not set),(not provided),False,Windows,Brazil,not available in demo dataset,ctbcnetsuper.com.br
23,None,1472782696,20160901,1,1,NaN,1.0,NaN,NaN,1.0,None,(not set),None,False,Macintosh,United States,New York,optonline.net
24,None,1472798836,20160901,1,1,NaN,1.0,NaN,NaN,1.0,None,(not set),(not provided),False,Windows,Taiwan,(not set),unknown.unknown
25,None,1472790511,20160901,1,1,NaN,1.0,NaN,NaN,1.0,None,(not set),(not provided),False,Windows,South Korea,Seoul,unknown.unknown
26,None,1472783030,20160901,1,1,NaN,1.0,NaN,NaN,1.0,None,(not set),None,True,Android,United States,(not set),google.com
27,None,1472723781,20160901,1,1,NaN,1.0,NaN,NaN,1.0,None,(not set),(not provided),False,Windows,Australia,not available in demo dataset,optusnet.com.au
28,None,1472730676,20160901,1,1,NaN,1.0,NaN,NaN,1.0,None,(not set),(not provided),False,Windows,Brazil,not available in demo dataset,veloxzone.com.br
29,None,1472732299,20160901,1,1,NaN,1.0,NaN,NaN,1.0,None,(not set),(not provided),False,Windows,Bulgaria,not available in demo dataset,cooolbox.bg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2657,None,1472764277,20160901,1,6,179.0,NaN,NaN,NaN,1.0,None,(not set),None,True,Android,United States,not available in demo dataset,(not set)
2658,None,1472745668,20160901,1,6,96.0,NaN,NaN,NaN,1.0,None,(not set),None,False,Windows,Dominican Republic,not available in demo dataset,gob.do
2659,None,1472717342,20160901,1,7,30.0,NaN,NaN,NaN,1.0,None,(not set),None,False,Windows,Australia,not available in demo dataset,optusnet.com.au
2660,None,1472741013,20160901,1,7,84.0,NaN,NaN,NaN,1.0,None,(not set),None,False,Windows,United States,not available in demo dataset,(not set)
2661,None,1472737491,20160901,1,7,188.0,NaN,NaN,NaN,1.0,None,(not set),None,False,Windows,Singapore,Singapore,unknown.unknown
2662,None,1472732517,20160901,1,7,110.0,NaN,NaN,NaN,1.0,None,(not set),None,False,Windows,Bangladesh,(not set),unknown.unknown
2663,None,1472757472,20160901,1,7,34.0,NaN,NaN,NaN,NaN,None,(not set),None,False,Windows,United States,not available in demo dataset,unknown.unknown
2664,None,1472745182,20160901,1,8,932.0,NaN,NaN,NaN,1.0,None,(not set),None,False,Linux,United States,Mountain View,(not set)
2665,None,1472766797,20160901,1,8,27.0,NaN,NaN,NaN,1.0,None,(not set),None,False,Windows,United States,not available in demo dataset,optonline.net
2666,None,1472751191,20160901,1,8,296.0,NaN,NaN,NaN,1.0,None,(not set),None,False,Windows,Benin,not available in demo dataset,unknown.unknown
2667,None,1472781802,20160901,1,8,173.0,NaN,NaN,NaN,1.0,None,(not set),None,False,Windows,Nepal,not available in demo dataset,hons.com.np
2668,None,1472739573,20160901,1,9,48.0,NaN,NaN,NaN,1.0,None,(not set),None,False,Windows,United States,not available in demo dataset,(not set)
2669,None,1472754724,20160901,1,9,102.0,NaN,NaN,NaN,NaN,None,(not set),None,False,Windows,United States,not available in demo dataset,wayport.net
2670,None,1472748875,20160901,1,10,617.0,NaN,NaN,NaN,1.0,None,(not set),None,False,Windows,Venezuela,not available in demo dataset,cantv.net
2671,None,1472751414,20160901,1,10,325.0,NaN,NaN,NaN,1.0,None,(not set),None,True,(not set),Kenya,Nairobi,opera-mini.net
2672,None,1472755571,20160901,1,10,208.0,NaN,NaN,NaN,1.0,None,(not set),None,False,Windows,United Kingdom,not available in demo dataset,virginm.net
2673,None,1472763500,20160901,1,10,138.0,NaN,NaN,NaN,1.0,None,(not set),None,False,Macintosh,Mexico,not available in demo dataset,megared.net.mx
2674,None,1472771547,20160901,1,10,95.0,NaN,NaN,NaN,NaN,None,(not set),None,True,iOS,United States,not available in demo dataset,(not set)
2675,None,1472740845,20160901,1,11,170.0,NaN,NaN,NaN,1.0,None,(not set),None,False,Windows,Brazil,not available in demo dataset,virtua.com.br
2676,None,1472777346,20160901,1,11,49.0,NaN,NaN,NaN,NaN,None,(not set),None,False,Linux,United States,Mountain View,(not set)
2677,None,1472773049,20160901,1,11,143.0,NaN,NaN,NaN,1.0,None,(not set),None,True,iOS,United States,Mountain View,(not set)
2678,None,1472748001,20160901,1,12,399.0,NaN,NaN,NaN,1.0,None,(not set),None,False,Macintosh,India,not available in demo dataset,iitr.ac.in
2679,None,1472759319,20160901,1,12,98.0,NaN,NaN,NaN,1.0,None,(not set),None,False,Windows,Canada,not available in demo dataset,burnaby.ca
2680,None,1472796676,20160901,1,13,93.0,NaN,NaN,NaN,1.0,None,(not set),None,False,Macintosh,United States,Sunnyvale,sbcglobal.net
2681,None,1472798819,20160901,1,13,335.0,NaN,NaN,NaN,1.0,None,(not set),None,False,Windows,India,not available in demo dataset,unknown.unknown
2682,None,1472757047,20160901,1,14,270.0,NaN,NaN,NaN,NaN,None,(not set),None,False,Windows,France,not available in demo dataset,unknown.unknown
2683,None,1472772090,20160901,1,14,151.0,NaN,1.0,25480000.0,NaN,None,(not set),None,False,Windows,United States,not available in demo dataset,(not set)
2684,None,1472737778,20160901,1,20,463.0,NaN,NaN,NaN,1.0,None,(not set),None,False,Windows,United States,not available in demo dataset,(not set)
2685,None,1472714118,20160901,1,38,1134.0,NaN,NaN,NaN,NaN,None,(not set),None,False,Windows,Japan,not available in demo dataset,ocn.ne.jp
2686,None,1472788273,20160901,1,77,2293.0,NaN,NaN,NaN,NaN,None,(not set),None,False,Windows,Thailand,Bangkok,unknown.unknown